# Generated by Django 4.2.2 on 2023-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('fatherName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر')),
                ('nationalCode', models.CharField(max_length=10, unique=True, verbose_name='کدملی')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه')),
                ('telephone', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره ثابت')),
                ('province', models.CharField(blank=True, max_length=18, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=18, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
