# Generated by Django 4.2.2 on 2023-06-19 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('isActive', models.BooleanField(default=True, verbose_name='آیا انبار فعال باشد؟')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='آیا انبار در لیست حذف شده ها باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_createdby', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorInventory', models.IntegerField(verbose_name='موجودی کف')),
                ('actualInventory', models.IntegerField(verbose_name='موجودی واقعی')),
                ('isActive', models.BooleanField(default=True, verbose_name='آیا فعال باشد')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='آیا در لیست حذف شده ها باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productId', to='product.product', verbose_name='شناسه محصول')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeId', to='store.store', verbose_name='شناسه انبار')),
            ],
            options={
                'db_table': 'productstore',
            },
        ),
    ]
