# Generated by Django 4.2.2 on 2023-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstore',
            options={'verbose_name': 'مدیریت انبار-محصول', 'verbose_name_plural': 'مدیریت انبارها-محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'انبار', 'verbose_name_plural': 'انبارها'},
        ),
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('1', 'عمومی'), ('2', 'واسط')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='actualInventory',
            field=models.IntegerField(verbose_name='موجودی قابل سفارش'),
        ),
    ]
