# Generated by Django 4.2.2 on 2023-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productstore_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('1', 'عمومی'), ('2', 'واسط')], default='1', max_length=255, verbose_name='نوع انبار'),
        ),
    ]
