# Generated by Django 4.2.2 on 2023-06-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('fatherName', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر')),
                ('nationalCode', models.CharField(max_length=10, unique=True, verbose_name='کدملی')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('mobile', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره همراه')),
                ('telephone', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره ثابت')),
                ('province', models.CharField(blank=True, max_length=18, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=18, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا کاربر فعال باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'db_table': 'customers',
            },
        ),
    ]
