# Generated by Django 4.2.2 on 2023-06-19 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('isActive', models.BooleanField(default=True, verbose_name='آیا محصول فعال باشد؟')),
                ('isStock', models.BooleanField(default=True, verbose_name='آیا محصول موجود می باشد؟')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='آیا محصول در لیست حذف شده ها باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_createdby', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
