# Generated by Django 4.2.2 on 2023-06-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='آیا محصول در لیست حذف شده ها باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه محصولات',
                'db_table': 'productgroups',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سایز کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='قیمت کالا')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='آیا محصول در لیست حذف شده ها باشد؟')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('productId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='شناسه کالا')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productgroupId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='product.productgroup'),
        ),
    ]
