# Generated by Django 4.2.2 on 2023-06-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productgroup_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'قیمت محصول', 'verbose_name_plural': 'قیمت محصولات'},
        ),
        migrations.AlterModelTable(
            name='productprice',
            table='productprice',
        ),
    ]
