# Generated by Django 4.2.2 on 2023-06-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productprice_options_alter_productprice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productgroupId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='product.productgroup', verbose_name='گروه محصول'),
        ),
    ]
