# Generated by Django 4.2.2 on 2023-06-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_productgroupid'),
        ('store', '0003_alter_store_type'),
        ('order', '0002_order_isactive_order_ispayment_order_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productId',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='order.order', verbose_name='شناسه سفارش')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='product.product', verbose_name='شناسه محصول')),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_detail', to='store.store', verbose_name='شناسه انبار')),
            ],
            options={
                'db_table': 'orders_detail',
            },
        ),
    ]
